// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

import (
	"github.com/DoNewsCode/core/contract"
)

// Injectors from wire.go:

func InjectKernel(env contract.Env) (Kernel, error) {
	kernel := Kernel{}
	return kernel, nil
}
